# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(706, 573)
        font = QtGui.QFont()
        font.setFamily("苹方 粗体")
        Dialog.setFont(font)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(120, 90, 371, 399))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_CreditHour = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CreditHour.setObjectName("lineEdit_CreditHour")
        self.gridLayout_2.addWidget(self.lineEdit_CreditHour, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEdit_CourseName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CourseName.setObjectName("lineEdit_CourseName")
        self.gridLayout_2.addWidget(self.lineEdit_CourseName, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_CourseNo = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CourseNo.setReadOnly(True)
        self.lineEdit_CourseNo.setObjectName("lineEdit_CourseNo")
        self.gridLayout_2.addWidget(self.lineEdit_CourseNo, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEdit_CourseHour = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_CourseHour.setObjectName("lineEdit_CourseHour")
        self.gridLayout_2.addWidget(self.lineEdit_CourseHour, 3, 1, 1, 1)
        self.lineEdit_PriorCourse = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_PriorCourse.setObjectName("lineEdit_PriorCourse")
        self.gridLayout_2.addWidget(self.lineEdit_PriorCourse, 4, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 190, 101, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_OK = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_OK.setObjectName("btn_OK")
        self.verticalLayout_2.addWidget(self.btn_OK)
        self.btn_Cancle = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_Cancle.setObjectName("btn_Cancle")
        self.verticalLayout_2.addWidget(self.btn_Cancle)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "CourseName(课程名)"))
        self.label_7.setText(_translate("Dialog", "CourseNo(课程号)"))
        self.label_8.setText(_translate("Dialog", "PriorCourse(先修课程)"))
        self.label_9.setText(_translate("Dialog", "CreditHour(学分)"))
        self.label_10.setText(_translate("Dialog", "CourseHour(课时)"))
        self.btn_OK.setText(_translate("Dialog", "确认"))
        self.btn_Cancle.setText(_translate("Dialog", "取消"))
