# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CourseInfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1011, 657)
        font = QtGui.QFont()
        font.setFamily("苹方 粗体")
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 961, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_CourseInfo = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget_CourseInfo.setObjectName("tableWidget_CourseInfo")
        self.tableWidget_CourseInfo.setColumnCount(0)
        self.tableWidget_CourseInfo.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_CourseInfo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_OK = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_OK.setObjectName("btn_OK")
        self.horizontalLayout.addWidget(self.btn_OK)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_Cancle = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Cancle.setObjectName("btn_Cancle")
        self.horizontalLayout.addWidget(self.btn_Cancle)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_OK.setText(_translate("Dialog", "确定"))
        self.btn_Cancle.setText(_translate("Dialog", "退出"))
