# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(726, 593)
        font = QtGui.QFont()
        font.setFamily("苹方 粗体")
        font.setPointSize(9)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 200, 101, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_OK = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_OK.setObjectName("btn_OK")
        self.verticalLayout.addWidget(self.btn_OK)
        self.btn_Cancle = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Cancle.setObjectName("btn_Cancle")
        self.verticalLayout.addWidget(self.btn_Cancle)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 100, 371, 399))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_CreditHour = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_CreditHour.setReadOnly(True)
        self.lineEdit_CreditHour.setObjectName("lineEdit_CreditHour")
        self.gridLayout.addWidget(self.lineEdit_CreditHour, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_CourseName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_CourseName.setReadOnly(True)
        self.lineEdit_CourseName.setObjectName("lineEdit_CourseName")
        self.gridLayout.addWidget(self.lineEdit_CourseName, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_CourseNo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_CourseNo.setReadOnly(True)
        self.lineEdit_CourseNo.setObjectName("lineEdit_CourseNo")
        self.gridLayout.addWidget(self.lineEdit_CourseNo, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_CourseHour = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_CourseHour.setReadOnly(True)
        self.lineEdit_CourseHour.setObjectName("lineEdit_CourseHour")
        self.gridLayout.addWidget(self.lineEdit_CourseHour, 3, 1, 1, 1)
        self.lineEdit_PriorCourse = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_PriorCourse.setReadOnly(True)
        self.lineEdit_PriorCourse.setObjectName("lineEdit_PriorCourse")
        self.gridLayout.addWidget(self.lineEdit_PriorCourse, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_OK.setText(_translate("Dialog", "确认"))
        self.btn_Cancle.setText(_translate("Dialog", "取消"))
        self.label_2.setText(_translate("Dialog", "CourseName(课程名)"))
        self.label.setText(_translate("Dialog", "CourseNo(课程号)"))
        self.label_5.setText(_translate("Dialog", "PriorCourse(先修课程)"))
        self.label_3.setText(_translate("Dialog", "CreditHour(学分)"))
        self.label_4.setText(_translate("Dialog", "CourseHour(课时)"))
