# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("苹方 粗体")
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 801, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_classinfo = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget_classinfo.setObjectName("tableWidget_classinfo")
        self.tableWidget_classinfo.setColumnCount(0)
        self.tableWidget_classinfo.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_classinfo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_insert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_insert.setObjectName("btn_insert")
        self.horizontalLayout.addWidget(self.btn_insert)
        self.btn_alter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_alter.setObjectName("btn_alter")
        self.horizontalLayout.addWidget(self.btn_alter)
        self.btn_delete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_classinfo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_classinfo.setObjectName("btn_classinfo")
        self.horizontalLayout.addWidget(self.btn_classinfo)
        self.btn_close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "课程信息维护"))
        self.btn_insert.setText(_translate("MainWindow", "增加"))
        self.btn_alter.setText(_translate("MainWindow", "修改"))
        self.btn_delete.setText(_translate("MainWindow", "删除"))
        self.btn_classinfo.setText(_translate("MainWindow", "选课情况"))
        self.btn_close.setText(_translate("MainWindow", "退出"))
